conditioning:
  method: mpgd
  params:
    scale: 0.3 # will be changed in another script

data:
  name: ffhq
  root: ./data/samples

measurement:
  operator:
    name: compressed_sensing
    in_shape: !!python/tuple [1, 3, 256, 256]
    cs_ratio: 0.3
  
  noise: 
    name: gaussian
    sigma: 0.05
